In [1]:
import numpy as np

In [4]:
A = np.array([[2/3, 1/3, 2/3], [-2/3, 2/3, 1/3], [1/3, 2/3, -2/3]])
print(A)

[[ 0.66666667  0.33333333  0.66666667]
 [-0.66666667  0.66666667  0.33333333]
 [ 0.33333333  0.66666667 -0.66666667]]


In [5]:
np.dot(A, A.T)

array([[ 1.00000000e+00, -1.23358114e-17,  2.46716228e-17],
       [-1.23358114e-17,  1.00000000e+00, -1.54197642e-17],
       [ 2.46716228e-17, -1.54197642e-17,  1.00000000e+00]])

In [6]:
A.dot(A.T)

array([[ 1.00000000e+00, -1.23358114e-17,  2.46716228e-17],
       [-1.23358114e-17,  1.00000000e+00, -1.54197642e-17],
       [ 2.46716228e-17, -1.54197642e-17,  1.00000000e+00]])

In [7]:
np.linalg.inv(A)

array([[ 0.66666667, -0.66666667,  0.33333333],
       [ 0.33333333,  0.66666667,  0.66666667],
       [ 0.66666667,  0.33333333, -0.66666667]])

In [8]:
np.dot(A.T, A)

array([[1.00000000e+00, 1.54197642e-17, 1.23358114e-17],
       [1.54197642e-17, 1.00000000e+00, 2.46716228e-17],
       [1.23358114e-17, 2.46716228e-17, 1.00000000e+00]])

In [9]:
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
B = np.array([[2, 0, -1], [-2, 3, 1], [0, 4, -1]])
U1 = np.array([2, 5, -3])
U2 = np.array([0, -4, 6])
U = np.array([[2, 0], [5, -4], [-3, 6]])

In [15]:
np.dot(I, U1)

array([ 2.,  5., -3.])

In [16]:
np.dot(B, U1)

array([ 7,  8, 23])

In [18]:
np.dot(B, U2)

array([ -6,  -6, -22])

In [17]:
np.dot(B, U)

array([[  7,  -6],
       [  8,  -6],
       [ 23, -22]])