In [1]:
import numpy as np

In [2]:
a = np.arange(10)
print(a)
print(a + 1)
print(a ** 2)

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[ 0  1  4  9 16 25 36 49 64 81]


In [3]:
print(a)
b = np.ones(10) + 1
print(b)
print(a - b)
print(a * b)

[0 1 2 3 4 5 6 7 8 9]
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
[-2. -1.  0.  1.  2.  3.  4.  5.  6.  7.]
[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]


In [4]:
c = np.diag([1, 2, 3, 4])
print(c)
print(c * c)
print("********************")
print(c.dot(c))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
********************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [5]:
a = np.array([1, 3, 5, 7, 9])
b = np.array([2, 3, 6, 7, 10])
print(a == b)
print(a > b)

[False  True False  True False]
[False False False False False]


In [6]:
a = np.array([1, 3, 5, 7, 9])
b = np.array([2, 3, 6, 7, 10])
c = np.array([2, 3, 6, 7, 10])

print(np.array_equal(a, b))
print(np.array_equal(b, c))

False
True


In [7]:
a = np.array([0, 0, 1, 1, 0, 1, 1])
b = np.array([1, 0, 1, 0, 1, 1, 0])

print(np.logical_or(a, b))
print(np.logical_and(a, b))

[ True False  True  True  True  True  True]
[False False  True False False  True False]


In [8]:
a = np.arange(10)
print(np.sin(a))
print(np.log(a))
print(np.exp(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


/tmp/ipykernel_46397/3928490574.py:3: RuntimeWarning: divide by zero encountered in log
  print(np.log(a))


In [9]:
a = np.arange(10000)
print(np.sum(a))

49995000


In [10]:
a = np.array([[1,3], [2, 7]])
print(a.sum(axis=0)) #Column wise addition if axis = 0
print(a.sum(axis=1)) #Row wise addition if axis = 1

[ 3 10]
[4 9]


In [11]:
np.all([True, True])

True

In [12]:
data = np.loadtxt("populations.txt")
print(data)

[[ 1900. 30000.  4000. 48300.]
 [ 1901. 47200.  6100. 48200.]
 [ 1902. 70200.  9800. 41500.]
 [ 1903. 77400. 35200. 38200.]
 [ 1904. 36300. 59400. 40600.]
 [ 1905. 20600. 41700. 39800.]
 [ 1906. 18100. 19000. 38600.]
 [ 1907. 21400. 13000. 42300.]
 [ 1908. 22000.  8300. 44500.]
 [ 1909. 25400.  9100. 42100.]
 [ 1910. 27100.  7400. 46000.]
 [ 1911. 40300.  8000. 46800.]
 [ 1912. 57000. 12300. 43800.]
 [ 1913. 76600. 19500. 40900.]
 [ 1914. 52300. 45700. 39400.]
 [ 1915. 19500. 51100. 39000.]
 [ 1916. 11200. 29700. 36700.]
 [ 1917.  7600. 15800. 41800.]
 [ 1918. 14600.  9700. 43300.]
 [ 1919. 16200. 10100. 41300.]
 [ 1920. 24700.  8600. 47300.]]


In [13]:
pops = data[:, 1:]
pops

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [14]:
pops.std()

17929.041851090667

In [15]:
np.argmax(pops, axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2])

In [16]:
print("Hello")

Hello


In [17]:
import numpy as np
x = np.array([55, 77, 4, 22, 1, 0, -1, 22 , 101])
print(x.min())
print(x.max())
print(x.argmin()) #Returns the index of the min number
print(x.argmax()) #Returns the index of the max number

-1
101
6
8


In [18]:
x = np.array([55, 77, 4, 22, 1, 0, -1, 22 , 101])
print(np.any(x != 0))
print(np.any(x < 0))

True
True


In [19]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

print((a <= b) & (b <= c))
print(type((a <= b) & (b <= c)))
((a <= b) & (b <= c)).all()

[ True  True  True  True]
<class 'numpy.ndarray'>


True

#BroadCasting

In [31]:
# tile accepts two arguments. One is a ndArray and second is duplicate the elements in the row.
a = np.tile(np.arange(0, 40, 10), (3, 1))
print(a)
print(f"Dimension of array - {a.ndim}")
print("*******************")
a = np.tile(np.arange(0, 40, 10), (3, 2))
print(a)
print("*******************")
print(a.T)


[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
Dimension of array - 2
*******************
[[ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]]
*******************
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]
 [ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [21]:
a = np.tile(np.arange(0, 40, 10), (3, 1))
print(a)
b = np.array([0, 1, 2])
print(a.T + b)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [22]:
a = np.arange(0, 40, 10)  # One dimensional array
print(a.shape)
print(a)

print("***********************")
x_2d = np.array([[0], [10], [20], [30]])
print(x_2d)
print("***********************")
#To convert 1D to 2D array

array_2d = a[:, np.newaxis]
print(array_2d)

(4,)
[ 0 10 20 30]
***********************
[[ 0]
 [10]
 [20]
 [30]]
***********************
[[ 0]
 [10]
 [20]
 [30]]


In [23]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.ravel())
print(a.T.ravel())
b = a.ravel()
print(b)
print(b.reshape((2, 3)))
print(a)

[1 2 3 4 5 6]
[1 4 2 5 3 6]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [24]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a.ravel().reshape((3, 2))
print(b)
b[0][1] = 50
print(b)
print("**************")
print(a)

[[1 2]
 [3 4]
 [5 6]]
[[ 1 50]
 [ 3  4]
 [ 5  6]]
**************
[[ 1 50  3]
 [ 4  5  6]]


In [25]:
a = np.arange(4 * 3 * 2)
print(a)

print("Converting 1D to 3D")

a = a.reshape(4, 3, 2)
print(a)



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Converting 1D to 3D
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [26]:
print(a[0, 2, 1])

5


In [27]:
a = np.arange(4)
a.resize((8,))
print(a)

[0 1 2 3 0 0 0 0]


In [28]:
b = a
a.resize((4,), refcheck=False)
print(a)
print(b)

[0 1 2 3]
[0 1 2 3]


In [29]:
a = np.array([[5, 4, 6], [2, 3, 2]])
print(np.sort(a, axis=1))  # wont change the actual array
print(a)
a.sort(axis=1) # Changes array
print(a)

[[4 5 6]
 [2 2 3]]
[[5 4 6]
 [2 3 2]]
[[4 5 6]
 [2 2 3]]
