# 1D Array = Vector
# 2D Array = Matrix
# nD Array = Tensor  (n > 2)

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(a)
b = np.array([1, 'b', 2])
print(b)
print(type(b))

print(np.arange(10))
print(a ** 2)
print(b ** 2)

[ 1  2  3  4  5  6  7  8  9 10]
['1' 'b' '2']
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
[  1   4   9  16  25  36  49  64  81 100]


TypeError: ufunc 'square' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [ ]:
l = range(0, 1000)

%timeit [i ** 2 for i in l]

200 µs ± 4.4 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [ ]:
a = np.arange(1000)
%timeit a ** 2

989 ns ± 22.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
lst = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(a)
print(lst)
a

[ 1  2  3  4  5  6  7  8  9 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a.ndim

1

In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.ndim)
print(b.shape)  # shape returns the matrix notation - 2 x 3

2
(2, 3)


In [ ]:
c = np.array([[[1, 2], [3, 4]],[[4, 2], [7, 4]]])
print(c.ndim)
print(c.shape)

3
(2, 2, 2)


In [ ]:
print(np.arange(0, 10, 2))
print(np.linspace(0, 1, 6))

[0 2 4 6 8]
[0.  0.2 0.4 0.6 0.8 1. ]


In [ ]:
print(np.ones((3, 3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
print(np.eye(5,5))  #identity matrix

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
a = np.diag([1, 2, 3, 4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
np.diag(a)

array([1, 2, 3, 4])

In [ ]:
print(np.random.rand(10))

[0.88536087 0.31062213 0.221163   0.64628129 0.4096738  0.17185364
 0.39202255 0.74046164 0.29983729 0.01871849]


In [ ]:
print(np.random.randn(10))

[-0.036842   -0.36996782  1.10338873 -0.93886146  0.10463015 -0.08105889
 -0.43233682 -0.8230778   0.96844595  1.80812459]


In [ ]:
a = np.arange(10)
print(a)
print(a.dtype)

[0 1 2 3 4 5 6 7 8 9]
int64


In [ ]:
a = np.arange(10, dtype='float64')
print(a)
print(a.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64


In [ ]:
a = np.array([1 + 2j, 2 + 4j])
print(a.dtype)

complex128


In [ ]:
a = np.array([True, False, False, True])
print(a.dtype)

bool


In [ ]:
a = np.arange(10)
print(a)
print(a[5])
print(a[12])

[0 1 2 3 4 5 6 7 8 9]
5


IndexError: index 12 is out of bounds for axis 0 with size 10

In [ ]:
a = np.diag([1, 2, 3])
print(a)
print(a[2, 2])  #In numpy, row or column starts with 0, so its 3rd row, 3rd Column technically.

a[2, 1] = 5
print(a)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
3
[[1 0 0]
 [0 2 0]
 [0 5 3]]


In [ ]:
a = np.arange(10)
print(a)
print(a[1 : 8 : 2])  # start index : end index (exclusive) : step size

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7]


In [ ]:
a = np.arange(10)
print(a)
a[5 : ] = 10
print(a)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 10 10 10 10 10]


In [ ]:
a = np.arange(10)
print(a)
b = a[::2]
print(b)
print(np.shares_memory(a, b))

a[2] = 11
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
True
[ 0  1 11  3  4  5  6  7  8  9]
[ 0 11  4  6  8]


In [ ]:
a = np.arange(10)
print(a)
b = a[::2].copy()  # This will create a new array and assign to B
print(b)
print(np.shares_memory(a, b))

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
False


In [ ]:
a = np.random.randint(0, 20, 15)  #Create a vector (1D array) 15 random numbers between 0 t0 20
print(a)

mask = (a % 2 == 0)
extract_from_a = a[mask]
print(extract_from_a)

[13  6  1 10 12 14 19  6 10 15 15  7 11 17 14]
[ 6 10 12 14  6 10 14]


In [ ]:
a = np.arange(0, 100, 10)
print(a)
print(a[[2, 5, 2, 2, 6, 7]])

a[[2, 4]] = 200
print(a)

[ 0 10 20 30 40 50 60 70 80 90]
[20 50 20 20 60 70]
[  0  10 200  30 200  50  60  70  80  90]
